import { Avatar, Badge, Button, Drawer, Dropdown, Input, Layout, Menu, message } from 'antd'
import {
  AppstoreOutlined,
  BellOutlined,
  BookOutlined,
  ClockCircleOutlined,
  CommentOutlined,
  DownOutlined,
  FileSearchOutlined,
  HddOutlined,
  HistoryOutlined,
  LogoutOutlined,
  MenuUnfoldOutlined,
  PlusOutlined,
  RobotOutlined,
  RocketOutlined,
  SearchOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  UserOutlined,
} from '@ant