"""add harness checkpoints

Revision ID: 58b7b7115747
Revises: 6727223d45f9
Create Date: 2026-08-14 10:06:54.246521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58b7b7115747'
down_revision: Union[str, None] = '6727223d45f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harness_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('next_iteration', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harness_checkpoints_runtime'), 'harness_checkpoints', ['runtime'], unique=False)
    op.create_index(op.f('ix_harness_checkpoints_user_id'), 'harness_checkpoints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harness_checkpoints_user_id'), table_name='harness_checkpoints')
    op.drop_index(op.f('ix_harness_checkpoints_runtime'), table_name='harness_checkpoints')
    op.drop_table('harness_checkpoints')
    # ### end Alembic commands ###
